name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push backend image
      run: |
        docker build -t nubes-backend ./backend
        docker tag nubes-backend:latest 727218227857.dkr.ecr.us-west-1.amazonaws.com/nubes-backend:latest
        docker push 727218227857.dkr.ecr.us-west-1.amazonaws.com/nubes-backend:latest

    - name: Build, tag, and push frontend image
      run: |
        docker build -t nubes-frontend ./frontend
        docker tag nubes-frontend:latest 727218227857.dkr.ecr.us-west-1.amazonaws.com/nubes-frontend:latest
        docker push 727218227857.dkr.ecr.us-west-1.amazonaws.com/nubes-frontend:latest
